"use client";
import {isStairArea} from "../../lib/reviter/directory-stair-geometry.ts";
import {useState} from 'react';
import type {DirectoryArea, AreaMetadata} from '../../lib/reviter/directory-areas.ts';
import {directoryAreaLinks} from '../../lib/reviter/directory-areas.ts';
import type {DirectoryRoom,RoomPortal} from '../../lib/reviter/room-directory.ts';
import type {DirectoryModelFloor} from './directory-model.ts';

export function AreaInspector({area,floor,metadata,members,modelName,portals=floor.portals??[],related=[],onChoose,onRelated,onSave,onInspectDoor,onWalkability,onStairAccess,selectedRoom,onSpaceUse,stairArrivals=[]}:{area:DirectoryArea;floor:DirectoryModelFloor;metadata?:AreaMetadata;members:DirectoryRoom[];modelName:string;portals?:readonly RoomPortal[];related?:DirectoryRoom[];onChoose?:(r:DirectoryRoom)=>void;onRelated?:(r:DirectoryRoom)=>void;onSave?:(value:AreaMetadata)=>void;onInspectDoor?:(id:number)=>void;onWalkability?:(value:"walkable"|"void")=>void;onStairAccess?:(value:NonNullable<DirectoryRoom["stairAccess"]>)=>void;selectedRoom?:DirectoryRoom;onSpaceUse?:(value:"source"|"atrium"|"hallway"|"room")=>void;stairArrivals?:{room:DirectoryRoom;direction:"Up"|"Down";flightId?:number}[]}){
  const [editing,setEditing]=useState(false),[name,setName]=useState(metadata?.name??''),[notes,setNotes]=useState(metadata?.notes??''),[ids,setIds]=useState(metadata?.elementIds?.join(', ')??''),[error,setError]=useState('');
  const [doorUse,setDoorUse]=useState<NonNullable<AreaMetadata['circulationDoorUse']>>(metadata?.circulationDoorUse??'unknown');
  const links=portals.filter(p=>p.rooms.some(k=>area.roomKeys.includes(k)));
  const slabs=[...new Set(members.map(r=>floor.roomElevations[r.key]?.evidence).filter(Boolean))];
  const relatedFloors=[...new Map(related.map(r=>[r.levelId,r])).values()];
  const accessLinks=directoryAreaLinks(floor.areas,portals,floor.areaRelationships,floor.openings).filter(l=>l.areas.includes(area.key)).sort((a,b)=>Number(b.reported.length>0)-Number(a.reported.length>0));
  const walkability=<div className="directory-walkability"><strong>{area.walkability==="void"?"Void · no walkable floor":"Walkable area"}</strong>{area.walkability==="void"&&<p>Excluded from walking routes and 3D floor fills. The boundary remains selectable for review.</p>}{members.map(r=>r.walkabilityNotes&&<p key={r.key}>{r.walkabilityNotes}</p>)}{area.kind==="room"&&onWalkability&&<label>Walkability<select aria-label="Area walkability" value={area.walkability??"walkable"} onChange={e=>onWalkability(e.target.value as "walkable"|"void")}><option value="walkable">Walkable floor</option><option value="void">Void / drop · no floor</option></select></label>}</div>;
  function save(){const values=ids.trim()?ids.split(/[\s,]+/).map(Number):[];if(values.length>1000||values.some(v=>!Number.isSafeInteger(v)||v<=0)){setError('Use positive model element IDs separated by commas.');return;}onSave?.({...metadata,name:name.trim(),notes:notes.trim(),elementIds:[...new Set(values)],...(area.kind!=='room'?{circulationDoorUse:doorUse}:{})});setEditing(false);setError('');}
  return <details className="directory-area-inspector" open><summary>Selected area · {metadata?.name||area.title} · {members.length} source {members.length===1?'record':'records'}</summary><div className="directory-area-content">
    <dl className="directory-area-facts"><div><dt>Building / level</dt><dd>{area.building} · #{area.levelId} · {area.elevation.toFixed(2)} ft</dd></div><div><dt>Area</dt><dd>{(area.areaFeet*.092903).toFixed(1)} m² · {area.polygons.length} {area.polygons.length===1?'outline':'separate outlines'}</dd></div><div><dt>Model</dt><dd>{modelName}</dd></div><div><dt>Area ID</dt><dd>{area.key}</dd></div></dl>
    {members.some(r=>r.spaceUse)&&<section aria-label="Reviewed area use"><strong>{area.kind==='atrium'?'Shared atrium':area.kind==='hallway'?'Shared circulation':'Separate room'} · user reported</strong><p>Original source names, IDs and boundaries are retained. Shared fills combine touching outlines at the same height; enclosed rooms and voids remain excluded.</p>{[...new Set(members.map(r=>r.spaceUse?.notes).filter(Boolean))].map(note=><p key={note}>{note}</p>)}</section>}
    {selectedRoom&&onSpaceUse&&<label className="directory-walkability">Selected source record use · {selectedRoom.number??selectedRoom.name}<select aria-label="Selected source record use" value={selectedRoom.spaceUse?.kind??"source"} onChange={e=>onSpaceUse(e.target.value as "source"|"atrium"|"hallway"|"room")}><option value="source">Use original source name</option><option value="atrium">Shared atrium · user reported</option><option value="hallway">Shared circulation · user reported</option><option value="room">Separate room · user reported</option></select></label>}
    {area.kind==="room"&&members.some(isStairArea)&&<section className="directory-stair-inspector" aria-label="Stair flight and landing"><strong>Stair flight and landing</strong>{!floor.stairFootprints?.some(f=>area.roomKeys.includes(f.roomKey))&&<p className="directory-connection-pending">No native tread geometry recovered for this source stair outline. Review the flight and its arrival floor. Native floor openings are excluded from flat-floor fills and walking routes. If no opening mask or flight geometry is recovered, the source outline stays visible in 3D without a flat fill across the shaft.</p>}<p>The source room outline includes surrounding landing space. Green steps are reviewed circulation within the same storey. Purple marks stair-flight treads below the plan cut; overhead treads are hidden on the floor map.</p>{floor.stairFootprints?.filter(f=>area.roomKeys.includes(f.roomKey)).map(f=><p key={f.roomKey}>Native step projections, including overhead flights: {(f.areaFeet*.092903).toFixed(1)} m²; source outline {(area.areaFeet*.092903).toFixed(1)} m².{!!f.stairElementIds.length&&` Native stair ${f.stairElementIds.map(id=>`#${id}`).join(', ')}.`}</p>)}{members.map(r=>r.stairAccessNotes&&<p key={r.key}>{r.stairAccessNotes}</p>)}{members[0]?.stairAccess==="local-only"&&<p>Local steps / landing only. Excluded from routes between storeys; walking access on this floor remains available.</p>}{onStairAccess&&<label>Storey connection<select aria-label="Stair storey connection" value={members[0]?.stairAccess??"unreviewed"} onChange={e=>onStairAccess(e.target.value as NonNullable<DirectoryRoom["stairAccess"]>)}><option value="unreviewed">Not reviewed · use native evidence</option><option value="flight-and-landing">Only the flight connects storeys</option><option value="up-flight-only">Upward flight connects · downward steps local</option><option value="local-only">Local steps / landing · no storey connection</option></select></label>}{members[0]?.stairAccess==="up-flight-only"&&<p>The upward flight can be used in both directions between these storeys. Local downward steps do not create a link to a lower storey.</p>}{members.some(r=>r.stairFlightIds?.length)&&<p>Reviewed native flight coverage: {members.flatMap(r=>r.stairFlightIds??[]).map(id=>`#${id}`).join(", ")}. Physical treads extend beyond the approximate source outline at their actual heights; the room boundary and its holes are retained.</p>}{!!stairArrivals.length&&<div aria-label="Matched stair arrivals"><strong>Matched stair arrivals</strong>{stairArrivals.map(a=><p key={a.room.key}><button className="rv-button" disabled={!onChoose} onClick={()=>onChoose?.(a.room)}>{a.direction} to {a.room.number} · level #{a.room.levelId}</button>{a.flightId!=null&&` · native flight #${a.flightId}`}</p>)}<p>These are matched flights. Walking access between the surrounding rooms still depends on recovered entrances.</p></div>}<p>A room label alone never creates a route to another floor.</p></section>}
    {members.some(r=>r.routePointFeet)&&<p>Reviewed landing arrival: {members.filter(r=>r.routePointFeet).map(r=>`X ${r.routePointFeet![0].toFixed(2)} · Y ${r.routePointFeet![1].toFixed(2)} ft`).join("; ")}. Original source labels are retained.</p>}
    {area.walkability==="void"&&walkability}
    <div className="directory-circulation-context"><strong>Area connections</strong>{metadata?.circulationDoorUse&&metadata.circulationDoorUse!=='unknown'&&<p className="directory-door-use">Usual door use: {metadata.circulationDoorUse==='usually-open'?'usually open':'usually closed'} (user reported)</p>}{accessLinks.map(link=>{const neighbour=floor.areas.find(a=>a.key===link.areas.find(k=>k!==area.key))!,r=floor.rooms.find(r=>r.key===neighbour.roomKeys[0]);return <div key={neighbour.key}><p>{floor.areaMetadata?.[neighbour.key]?.name||neighbour.title}{!!link.doorIds.length&&` · ${link.doorIds.length} recovered door ${link.doorIds.length===1?'link':'links'}`}{!!link.openIds.length&&` · ${link.openIds.length} verified open ${link.openIds.length===1?"boundary":"boundaries"}`}{!!link.reported.length&&` · ${link.reported.some(l=>l.kind==='open-space')?'open space':'connected access'} (user reported)`}</p>{link.riseFeet>.05&&<p className="directory-connection-pending">Height change: {link.riseFeet.toFixed(2)} ft. Check the stair or ramp transition; these areas are not one flat floor.</p>}{link.reported.length>0&&link.doorIds.length===0&&link.openIds.length===0&&<p className="directory-connection-pending">Opening location and route need review.</p>}{r&&onChoose&&<button className="rv-button" onClick={()=>onChoose(r)}>Select {neighbour.title}</button>}<div className="directory-area-chips">{link.doorIds.map(id=><button key={id} disabled={!onInspectDoor} onClick={()=>onInspectDoor?.(id)}>Door #{id}</button>)}</div>{link.reported.map((r,i)=>r.notes&&<p key={i}>{r.notes}</p>)}</div>;})}{!accessLinks.length&&<p>No matched access connection in the current boundaries. Select a nearby door to review its sides.</p>}</div>
    {area.walkability!=="void"&&walkability}
    {metadata?.notes&&<p>{metadata.notes}</p>}
    {area.geometryNeedsReview&&<p>Outline merging needs review. Original boundaries are retained.</p>}
    {!!metadata?.elementIds?.length&&<p>Associated model element IDs: {metadata.elementIds.join(', ')}</p>}
    <details><summary>Source records and model relationships</summary>
      {members.some(r=>r.modelSurface)&&<p>Model floor surfaces: {[...new Set(members.filter(r=>r.modelSurface).map(r=>`#${r.modelSurface!.elementId} · level #${r.modelSurface!.levelId} · ${r.modelSurface!.elevationFeet.toFixed(2)} ft`))].join(" · ")}. Native slab holes remain open.</p>}
      <p>Source drawings: {[...new Set(members.map(r=>r.dwg?.sectionId).filter(Boolean))].join(' · ')||'No drawing record; recovered from model geometry'}</p>
      <p>Slab relationships: {slabs.join(' · ')||'No slab match'}</p>
      <p>{links.length} recovered door connections · source boundary confidence {Math.round(Math.min(...members.map(r=>r.confidence))*100)}%.</p>
      <div className="directory-area-chips">{members.map(r=><button key={r.key} onClick={()=>onChoose?.(r)} disabled={!onChoose}>{r.number} · {r.name}</button>)}</div>
      {!!links.length&&<div className="directory-area-chips">{links.map(p=><button key={p.doorId} disabled={!onInspectDoor} onClick={()=>onInspectDoor?.(p.doorId)}>Door #{p.doorId}</button>)}</div>}
      {!!relatedFloors.length&&<><p>Related atrium records on other floors (a relationship, not a stair connection):</p><div className="directory-area-chips">{relatedFloors.map(r=><button key={r.levelId} disabled={!onRelated} onClick={()=>onRelated?.(r)}>Level #{r.levelId} · {r.dwg?.sectionId??r.number}</button>)}</div></>}
      <details><summary>Original record metadata</summary><pre>{JSON.stringify(members.map(({polygonFeet,holesFeet,...record})=>({...record,boundaryVertices:polygonFeet.length,holes:holesFeet?.length??0})),null,2)}</pre></details>
    </details>
    {onSave&&!editing&&<button className="rv-button" onClick={()=>{setName(metadata?.name??'');setNotes(metadata?.notes??'');setIds(metadata?.elementIds?.join(', ')??'');setDoorUse(metadata?.circulationDoorUse??'unknown');setEditing(true);}}>Associate area metadata</button>}
    {editing&&<div className="directory-area-form"><label>Area name<input maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><label>Area notes<textarea maxLength={10000} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{area.kind!=='room'&&<label>Circulation door use<select value={doorUse} onChange={e=>setDoorUse(e.target.value as typeof doorUse)}><option value="unknown">Unknown</option><option value="usually-open">Usually open · user reported</option><option value="usually-closed">Usually closed · user reported</option></select></label>}<label>Associated model element IDs<input value={ids} onChange={e=>setIds(e.target.value)} placeholder="e.g. 2471813, 1500816"/></label>{error&&<p role="alert">{error}</p>}<div><button className="rv-button" onClick={save}>Save area metadata</button><button className="rv-button" onClick={()=>setEditing(false)}>Cancel metadata edit</button></div></div>}
  </div></details>;
}
