import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,rm,copyFile,access} from 'node:fs/promises';
import {writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL,fileURLToPath} from 'node:url';import {spawn} from 'node:child_process';
import {createCheckpointBinding,runBoundedCheckpointTasks,readCheckpointResult,strictJson,type CheckpointTask} from '../scripts/indoor/bounded-worker-checkpoints.ts';
const worker=new URL('./fixtures/bounded-checkpoint-worker.mjs',import.meta.url);
async function fixture(){const directory=await mkdtemp(join(tmpdir(),'reviter-checkpoint-'));const input=join(directory,'input.json');await writeFile(input,JSON.stringify({offset:10}));return {directory,input,async binding(module=worker,version='test-v1'){return createCheckpointBinding({immutableInputs:[{name:'dataset',path:input}],algorithmFiles:[fileURLToPath(module)],algorithmVersion:version});},async close(){await rm(directory,{recursive:true,force:true});}};}
const tasks:CheckpointTask[]=[{id:'a',input:{value:1,delay:90},estimatedMemoryBytes:4096},{id:'b',input:{value:2,delay:5},estimatedMemoryBytes:4096},{id:'c',input:{value:3,delay:15},estimatedMemoryBytes:4096}];
test('out-of-order workers merge in task order, durable results resume without workers',async()=>{const f=await fixture();try{const binding=await f.binding(),order:string[]=[];const options={workerModule:worker,checkpointDir:join(f.directory,'results'),binding,tasks,maxWorkers:2,maxInFlightBytes:8192};const a=await runBoundedCheckpointTasks({...options,onProgress:e=>order.push(e.id)});assert.equal(order[0],'b');assert.deepEqual(a.results.map(r=>r.id),['a','b','c']);assert.deepEqual(await Promise.all(a.results.map(r=>readCheckpointResult(r))),[{value:11,padding:''},{value:12,padding:''},{value:13,padding:''}]);assert.equal(a.peakWorkers,2);assert(a.peakInFlightBytes<=8192);const b=await runBoundedCheckpointTasks(options);assert(b.results.every(r=>r.reused));assert.equal(b.peakWorkers,0);}finally{await f.close();}});
test('simultaneous completion while persistence is deliberately slow cannot lose results',async()=>{const f=await fixture();try{const output=await runBoundedCheckpointTasks({workerModule:worker,checkpointDir:join(f.directory,'results'),binding:await f.binding(),tasks:Array.from({length:12},(_,i)=>({id:String(i),input:{value:i,delay:0},estimatedMemoryBytes:4096})),maxWorkers:2,maxInFlightBytes:8192,beforeCheckpointCommit:async()=>{await new Promise(done=>setTimeout(done,20));}});assert.equal(output.results.length,12);assert(output.results.every(r=>r!==undefined));for(let i=0;i<12;i++)assert.equal((await readCheckpointResult(output.results[i]! ) as {value:number}).value,i+10);}finally{await f.close();}});
test('corrupt results and changed task/input/algorithm bindings recompute only eligible checkpoints',async()=>{const f=await fixture();try{const bound=await f.binding(),options={workerModule:worker,checkpointDir:join(f.directory,'results'),binding:bound,tasks,maxWorkers:2,maxInFlightBytes:8192};const a=await runBoundedCheckpointTasks(options);await writeFile(a.results[1]!.path,'corrupt');const b=await runBoundedCheckpointTasks(options);assert.deepEqual(b.results.map(r=>r.reused),[true,false,true]);const changed=structuredClone(tasks);changed[2]!.input={value:99};const c=await runBoundedCheckpointTasks({...options,tasks:changed});assert.deepEqual(c.results.map(r=>r.reused),[true,true,false]);await writeFile(f.input,JSON.stringify({offset:20}));await assert.rejects(runBoundedCheckpointTasks(options),/Stale checkpoint input/);const d=await runBoundedCheckpointTasks({...options,binding:await f.binding()});assert(d.results.every(r=>!r.reused));const e=await runBoundedCheckpointTasks({...options,binding:await f.binding(worker,'changed-algorithm-v2')});assert(e.results.every(r=>!r.reused));const copy=join(f.directory,'worker.mjs');await copyFile(worker,copy);const module=pathToFileURL(copy),old=await f.binding(module);await writeFile(copy,(await readFile(copy,'utf8'))+'\n// changed algorithm bytes\n');await assert.rejects(runBoundedCheckpointTasks({...options,workerModule:module,binding:old}),/Stale checkpoint input or algorithm/);}finally{await f.close();}});
test('worker errors preserve completed results and permit resume; unexpected exits reject',async()=>{const f=await fixture();try{const binding=await f.binding(),jobs:CheckpointTask[]=[{id:'first',input:{value:1,delay:5},estimatedMemoryBytes:4096},{id:'second',input:{value:2,delay:80,fail:true},estimatedMemoryBytes:4096},{id:'third',input:{value:3,delay:200},estimatedMemoryBytes:4096}],options={workerModule:worker,checkpointDir:join(f.directory,'results'),binding,tasks:jobs,maxWorkers:2,maxInFlightBytes:8192};await assert.rejects(runBoundedCheckpointTasks(options),/Deliberate worker failure/);jobs[1]!.input={value:2,delay:1};const resumed=await runBoundedCheckpointTasks(options);assert.equal(resumed.results[0]!.reused,true);assert.equal(resumed.results[1]!.reused,false);await assert.rejects(runBoundedCheckpointTasks({...options,checkpointDir:join(f.directory,'exit'),tasks:[{id:'exit',input:{value:1,exit:true},estimatedMemoryBytes:4096}]}),/Worker exited during task/);}finally{await f.close();}});
test('worker count, declared base/task memory and result limits stay bounded',async()=>{const f=await fixture();try{const base={workerModule:worker,checkpointDir:join(f.directory,'results'),binding:await f.binding(),tasks,maxWorkers:4,maxInFlightBytes:3500,workerMemoryBytes:1000};const jobs=tasks.map(t=>({...t,estimatedMemoryBytes:1500}));const r=await runBoundedCheckpointTasks({...base,tasks:jobs});assert.equal(r.peakWorkers,1);assert(r.peakInFlightBytes<=3500);await assert.rejects(runBoundedCheckpointTasks({...base,tasks:[{id:'large',input:null,estimatedMemoryBytes:5000}]}),/exceeds memory budget/);await assert.rejects(runBoundedCheckpointTasks({...base,maxWorkers:0}),/Invalid bounded worker limits/);await assert.rejects(runBoundedCheckpointTasks({...base,tasks:jobs,maxResultBytes:1,checkpointDir:join(f.directory,'too-large')}),/result exceeds/);await assert.rejects(runBoundedCheckpointTasks({...base,tasks:[{id:'invalid',input:{value:1,invalid:true},estimatedMemoryBytes:1500}],checkpointDir:join(f.directory,'invalid')}),/lossless JSON carrier/);}finally{await f.close();}});
test('lossless carriers reject Rational-like prototypes, BigInt, accessors, sparse arrays and implicit toJSON',()=>{class RationalLike{n=1n;d=3n;toJSON(){return 0.333;}}assert.throws(()=>strictJson(new RationalLike()),/lossless/);for(const x of [1n,undefined,NaN,Infinity,-0,new Date(),new Map(),{toJSON:()=>1},[,,]])assert.throws(()=>strictJson(x));const a={};Object.defineProperty(a,'x',{enumerable:true,get(){throw Error('getter must not run');}});assert.throws(()=>strictJson(a),/accessors/);assert.equal(strictJson({exact:[['1','3'],['0','1']]}),' {"exact":[["1","3"],["0","1"]]}'.trim());});
test('array subclasses, own toJSON, indexed getters and symbol properties never execute serialization hooks',()=>{let called=false;class ArraySubclass extends Array<number>{toJSON(){called=true;return [99];}}assert.throws(()=>strictJson(new ArraySubclass(1)));const own=[1];Object.defineProperty(own,'toJSON',{enumerable:true,value:()=>{called=true;return [99];}});assert.throws(()=>strictJson(own));const getter=[1];Object.defineProperty(getter,'0',{enumerable:true,get(){called=true;return 99;}});assert.throws(()=>strictJson(getter),/accessors/);const symbol=[1];Object.defineProperty(symbol,Symbol('extra'),{value:2});assert.throws(()=>strictJson(symbol));assert.equal(called,false);});
test('a live runner lock is never taken; a killed subprocess resumes durable work',async()=>{const f=await fixture();try{const directory=join(f.directory,'results'),child=spawn(process.execPath,['--experimental-strip-types',fileURLToPath(new URL('./fixtures/bounded-checkpoint-crash-runner.mjs',import.meta.url)),directory,f.input],{stdio:['ignore','pipe','pipe']});let stderr='';child.stderr.on('data',b=>stderr+=b);await new Promise<void>((done,fail)=>{const timer=setTimeout(()=>fail(Error('Child did not checkpoint: '+stderr)),10000);child.stdout.on('data',b=>{if(String(b).includes('FIRST_DURABLE')){clearTimeout(timer);done();}});child.once('exit',()=>{clearTimeout(timer);fail(Error('Child exited before checkpoint: '+stderr));});});const binding=await f.binding(),options={workerModule:worker,checkpointDir:directory,binding,maxWorkers:2,maxInFlightBytes:8192,tasks:[{id:'first',input:{value:1,delay:5},estimatedMemoryBytes:4096},{id:'second',input:{value:2,delay:60000},estimatedMemoryBytes:4096}]};await assert.rejects(runBoundedCheckpointTasks(options),/live runner/);child.kill('SIGKILL');await new Promise(done=>child.once('exit',done));options.tasks[1]!.input={value:2,delay:1};const resumed=await runBoundedCheckpointTasks(options);assert.equal(resumed.results[0]!.reused,true);assert.equal(resumed.results[1]!.reused,false);await assert.rejects(access(join(directory,'.runner-lock')));}finally{await f.close();}});

test('numeric-looking non-index array properties must not disappear from a carrier',()=>{for(const key of ['4294967295','9007199254740993','01','1.0','-0','-1']){const value=[1];Object.defineProperty(value,key,{enumerable:true,value:2});assert.throws(()=>strictJson(value),/plain array/);}});
test('a cached result never bypasses a smaller caller result or task-memory budget',async()=>{
 const f=await fixture();try{
  const options={workerModule:worker,checkpointDir:join(f.directory,'results'),binding:await f.binding(),tasks:[{id:'padded',input:{value:1,padding:256},estimatedMemoryBytes:4096}],maxWorkers:1,maxInFlightBytes:4096};
  const first=await runBoundedCheckpointTasks(options);assert(first.results[0]!.resultBytes>128);
  await assert.rejects(runBoundedCheckpointTasks({...options,maxResultBytes:128}),/result exceeds/);
  await assert.rejects(runBoundedCheckpointTasks({...options,tasks:[{...options.tasks[0]!,estimatedMemoryBytes:128}]}),/result exceeds/);
  const restored=await runBoundedCheckpointTasks(options);assert.equal(restored.results[0]!.reused,true);
 }finally{await f.close();}
});
test('all-checkpoint reuse still revalidates bound source bytes before returning',async()=>{
 const f=await fixture();try{
  const options={workerModule:worker,checkpointDir:join(f.directory,'results'),binding:await f.binding(),tasks:[tasks[0]!],maxWorkers:1,maxInFlightBytes:4096};
  await runBoundedCheckpointTasks(options);
  await assert.rejects(runBoundedCheckpointTasks({...options,onProgress:()=>{writeFileSync(f.input,JSON.stringify({offset:99}));}}),/Stale checkpoint input/);
 }finally{await f.close();}
});
