import {test} from 'node:test';import assert from 'node:assert/strict';
import {validateCadCirculationReview,cadInterpretedGeometry,type CadCirculationReview} from '../lib/reviter/dwg-circulation-review.ts';
const geometry={sourceSha256:'source',floors:[{id:'f',doors:[],stairs:[],primitives:[{sourceHandle:'a',type:'LINE',pointsMetres:[[0,0],[1,0]] as [number,number][]},{sourceHandle:'b',type:'LINE',pointsMetres:[[1.001,-1],[1.001,1]] as [number,number][]}]}]};
function fixture():CadCirculationReview{return {format:'reviter-cad-circulation-review',version:1,sourceSha256:'source',geometrySha256:'geometry',appliedToNativeGeometry:false,routingEligible:false,graphEdges:[],maximumContactGapMetres:.002,floors:[{floorId:'f',doors:[],contacts:[{id:'contact',fromHandle:'a',fromSegmentIndex:0,fromEndpointIndex:1,toHandle:'b',toSegmentIndex:0,toFraction:.5,pointsMetres:[[1,0],[1.001,0]],gapMetres:.001,maximumGapMetres:.002,selectionOnly:true}],assessment:{beforeClosedLabels:0,afterClosedLabels:0,sharedLabels:[],missingLabels:[]}}]};}
test('reconstructs original finite contact without changing original geometry',()=>{const original=JSON.stringify(geometry),review=validateCadCirculationReview(fixture(),geometry,'geometry');const interpreted=cadInterpretedGeometry(geometry,review);assert.notEqual(interpreted,geometry);assert.equal(JSON.stringify(geometry),original);});
test('refuses stale, moved, widened and unsupported finite contact proofs',()=>{for(const change of ['hash','endpoint','fraction','gap','native']){const review=fixture();if(change==='hash')review.geometrySha256='other';if(change==='endpoint')review.floors[0]!.contacts[0]!.pointsMetres[0]=[.99,0];if(change==='fraction')review.floors[0]!.contacts[0]!.toFraction=.51;if(change==='gap')review.maximumContactGapMetres=.1;if(change==='native')review.appliedToNativeGeometry=true as false;assert.throws(()=>validateCadCirculationReview(review,geometry,'geometry'),/finite source evidence/);}});
test('never derives a contact from a stair source stroke',()=>{const g=structuredClone(geometry);g.floors[0]!.stairs=[{sourceHandles:['b']}] as never[];assert.throws(()=>validateCadCirculationReview(fixture(),g,'geometry'));});
function leafFixture(){
 const points=Array.from({length:17},(_,i)=>[Math.cos(i*Math.PI/32),Math.sin(i*Math.PI/32)] as [number,number]);
 const g={sourceSha256:'source',floors:[{id:'f',stairs:[],doors:[],primitives:[{sourceHandle:'arc',type:'ARC',pointsMetres:points,centreMetres:[0,.052] as [number,number],radiusMetres:1.00135,sweepRadians:Math.PI/2},{sourceHandle:'leaf',type:'LINE',pointsMetres:[[0,0],[0,1]] as [number,number][]},{sourceHandle:'left',type:'LINE',pointsMetres:[[-1,0],[0,0]] as [number,number][]},{sourceHandle:'right',type:'LINE',pointsMetres:[[1,0],[2,0]] as [number,number][]}]}]};
 const r=fixture();r.floors[0]!.contacts=[];r.floors[0]!.doors=[{id:'derived',floorId:'f',arcHandle:'arc',arcHandles:['arc'],hingeMetres:[0,0],widthMetres:1,closedLeafMetres:[[0,0],[1,0]],thresholdSegmentsMetres:[[[0,0],[1,0]]],leafHandles:['leaf'],leafSegmentsMetres:[[[0,0],[0,1]]],supportingWallHandles:['left','right'],swingPointsMetres:points,recognitionMethod:'finite-leaf-quarter-symbol',sourceLeafWitnesses:[{handle:'leaf',segmentIndex:0}],contactWitnesses:[{fromHandle:'left',fromSegmentIndex:0,fromPointMetres:[0,0],toHandle:'right',toSegmentIndex:0,toPointMetres:[1,0]}],routingEligible:false,access:null,nativeDoorId:null}];return {g,r};
}
test('displaced symbol needs an independent original radial leaf and finite jambs',()=>{const {g,r}=leafFixture();assert.equal(validateCadCirculationReview(r,g,'geometry'),r);const original=JSON.stringify(g),interpreted=cadInterpretedGeometry(g,r);assert.equal(interpreted.floors[0]!.doors.length,1);assert.equal(JSON.stringify(g),original);for(const kind of ['leaf','jamb','arc','width']){const {g,r}=leafFixture();if(kind==='leaf')r.floors[0]!.doors[0]!.sourceLeafWitnesses[0]!.handle='left';if(kind==='jamb')r.floors[0]!.doors[0]!.contactWitnesses[0]!.toPointMetres=[.99,0];if(kind==='arc')g.floors[0]!.primitives[0]!.centreMetres=[.5,.5];if(kind==='width')r.floors[0]!.doors[0]!.widthMetres=1.2;assert.throws(()=>validateCadCirculationReview(r,g,'geometry'));}});
test('paired stair riser proof excludes a symbol only at the finite original tread span',()=>{
 const g=structuredClone(geometry);g.floors[0]!.stairs=[{id:'stairs',sourceHandles:['tread'],treads:[{pointsMetres:[[0,0],[1,0]]}]}] as never[];
 g.floors[0]!.primitives.push({sourceHandle:'riser',type:'LINE',pointsMetres:[[0,.02],[1,.02]]});
 const r=fixture();r.floors[0]!.contacts=[];r.floors[0]!.stairRiserWitnesses=[{handle:'riser',segmentIndex:0,stairId:'stairs',treadIndex:0,pointsMetres:[[0,.02],[1,.02]],comparisonOnly:true,routingEligible:false}];
 const original=JSON.stringify(g);assert.equal(validateCadCirculationReview(r,g,'geometry'),r);assert.equal(JSON.stringify(g),original);
 for(const kind of ['railing','wide','moved','stale','native']){const copy=structuredClone(r),w=copy.floors[0]!.stairRiserWitnesses![0]!;if(kind==='railing')w.handle='b';if(kind==='wide'){const moved=structuredClone(g);moved.floors[0]!.primitives.at(-1)!.pointsMetres=[[0,.03],[1,.03]];w.pointsMetres=[[0,.03],[1,.03]];assert.throws(()=>validateCadCirculationReview(copy,moved,'geometry'));continue;}if(kind==='moved')w.pointsMetres[0]=[.001,.02];if(kind==='stale')w.treadIndex=1;if(kind==='native')w.routingEligible=true as false;assert.throws(()=>validateCadCirculationReview(copy,g,'geometry'));}
});
