import * as THREE from 'three';
import test from 'node:test';import assert from 'node:assert/strict';
import {fitGeoreference,geographicToLocalMetres,georeferencedSceneMatrix,parseGeoreference,modelPointToGeographic,geographicToModelPoint,geoToMapPixel,mapPixelToGeo,georeferencedRoomsGeoJSON,type ModelGeoreference} from '../lib/reviter/georeference.ts';
import {parseRoomDirectory,type DirectoryRoom} from '../lib/reviter/room-directory.ts';
const R=6378137,rad=Math.PI/180,origin={latitude:53.89,longitude:-122.814};
const registration=(scale=.3048,rotation=30):ModelGeoreference=>({format:'reviter-georeference',version:1,modelFileName:'model.rvt',coordinateSystem:'WGS84',method:'fixed-scale',points:([[-100,-50],[100,-50],[0,100]] as [number,number][]).map((modelFeet,i)=>{const a=rotation*rad,e=scale*(Math.cos(a)*modelFeet[0]-Math.sin(a)*modelFeet[1]),n=scale*(Math.sin(a)*modelFeet[0]+Math.cos(a)*modelFeet[1]);return{id:String(i),name:`Corner ${i}`,modelFeet,levelId:i===2?694:311,geographic:{latitude:origin.latitude+n/R/rad,longitude:origin.longitude+e/(R*Math.cos(origin.latitude*rad))/rad}};})});
test('reference pairs recover rotation and fixed Revit-foot scale without changing source points',()=>{const g=registration(),before=structuredClone(g),fit=fitGeoreference(g);assert.ok(Math.abs(fit.rotationDegrees-30)<1e-8);assert.equal(fit.scaleMetresPerFoot,.3048);assert.ok(fit.rmsMetres<1e-8);assert.deepEqual(g,before);assert.equal(fit.residuals.length,3);const p:[number,number]=[154.2,-32.7],round=geographicToModelPoint(modelPointToGeographic(p,fit),fit);assert.ok(Math.hypot(round[0]-p[0],round[1]-p[1])<1e-7);});
test('free-scale registration is explicit and fixed-scale residuals expose incorrect distances',()=>{const g=registration(.5,-48),fixed=fitGeoreference(g);assert.ok(fixed.rmsMetres>15);const fit=fitGeoreference({...g,method:'fit-scale'});assert.ok(Math.abs(fit.scaleMetresPerFoot-.5)<1e-9);assert.ok(Math.abs(fit.rotationDegrees+48)<1e-8);assert.ok(fit.rmsMetres<1e-8);});
test('an inconsistent third pair produces nonzero residuals rather than an undetected two-point alignment',()=>{const g=registration();g.points[2]!.geographic.latitude+=5/R/rad;const fit=fitGeoreference(g);assert.ok(fit.rmsMetres>1);assert.ok(fit.residuals.some(r=>r.metres>1));});
test('import preserves control points and model identity while rejecting invalid and degenerate registrations',()=>{const g=registration();assert.deepEqual(parseGeoreference(JSON.stringify(g)),g);const room:DirectoryRoom={key:'r',number:'05-100',levelId:311,confidence:1,polygonFeet:[[0,0],[10,0],[10,10]],labelPointFeet:[1,1]};const data={format:'reviter-room-annotations',version:1,coordinateSystem:'revit-model-feet',model:{fileName:'model.rvt'},annotations:[room],georeference:g};assert.deepEqual(parseRoomDirectory(JSON.stringify(data)),data);const dualName={...data,model:{fileName:'annotation-source.rvt'},georeference:{...g,sourceModelFileName:'annotation-source.rvt'}};assert.deepEqual(parseRoomDirectory(JSON.stringify(dualName)),dualName);assert.throws(()=>parseRoomDirectory(JSON.stringify({...data,georeference:{...g,modelFileName:'wrong.rvt'}})));for(const points of [[g.points[0],g.points[0]],[{...g.points[0],modelFeet:[null,0]}],[{...g.points[0],geographic:{latitude:90,longitude:0}}]])assert.throws(()=>parseGeoreference(JSON.stringify({...g,points})));assert.throws(()=>fitGeoreference({...g,points:[]}));assert.throws(()=>fitGeoreference({...g,points:g.points.map(p=>({...p,modelFeet:[0,0]}))}));assert.throws(()=>fitGeoreference({...g,points:g.points.map((p,i)=>({...p,geographic:{latitude:53+i,longitude:-122}}))}));});
test('geographic map pixels round-trip independently of the model registration',()=>{for(const zoom of [2,17,19])for(const p of [origin,{latitude:-38,longitude:144},{latitude:0,longitude:0}]){const round=mapPixelToGeo(geoToMapPixel(p,zoom),zoom);assert.ok(Math.abs(round.latitude-p.latitude)<1e-9);assert.ok(Math.abs(round.longitude-p.longitude)<1e-9);}});
test('GeoJSON exports longitude/latitude, closed correctly wound holes, level IDs and source provenance without altering the model',()=>{const g=registration(),room:DirectoryRoom={key:'r',number:'05-100',name:'Office',levelId:694,confidence:1,polygonFeet:[[0,0],[0,10],[10,10],[10,0]],holesFeet:[[[2,2],[8,2],[8,8],[2,8]]],labelPointFeet:[1,1],access:{kind:'staff',evidence:'user-reported'}},before=structuredClone(room);const out=georeferencedRoomsGeoJSON([room,{...room,key:'deleted',status:'deleted'}],g),f=out.features[0]!;assert.equal(out.features.length,1);assert.equal(f.properties.nativeLevelId,694);assert.equal(f.properties.access,'staff');assert.equal(f.geometry.coordinates.length,2);for(const ring of f.geometry.coordinates)assert.deepEqual(ring[0],ring.at(-1));assert.ok(f.geometry.coordinates[0]![0]![0]!<0);assert.ok(f.geometry.coordinates[0]![0]![1]!>0);const signed=(ring:number[][])=>ring.slice(1).reduce((sum,p,j)=>sum+ring[j]![0]!*p[1]!-p[0]!*ring[j]![1]!,0);assert.ok(signed(f.geometry.coordinates[0]!)>0);assert.ok(signed(f.geometry.coordinates[1]!)<0);assert.deepEqual(room,before);});

test('3D registration matches the geographic overlay, preserves vertical feet and transforms cut planes consistently',()=>{
  const g={...registration(.5,72),method:'fit-scale' as const},fit=fitGeoreference(g),originFeet={x:1200,y:-450,z:28},base=14.44;
  const matrix=new THREE.Matrix4().fromArray(georeferencedSceneMatrix(fit,originFeet,base));
  const p=[1490,-320,24.28];
  const scenePoint=new THREE.Vector3(p[0]!-originFeet.x,p[1]!-originFeet.y,p[2]!-originFeet.z).applyMatrix4(matrix);
  const [east,north]=geographicToLocalMetres(modelPointToGeographic([p[0]!,p[1]!],fit),fit);
  assert.ok(Math.abs(scenePoint.x-east)<1e-7);assert.ok(Math.abs(scenePoint.y-north)<1e-7);
  assert.ok(Math.abs(scenePoint.z-(24.28-base)*.3048)<1e-10);
  const next=new THREE.Vector3(p[0]!-originFeet.x,p[1]!-originFeet.y,p[2]!+10-originFeet.z).applyMatrix4(matrix);
  assert.ok(Math.abs(next.z-scenePoint.z-3.048)<1e-10);
  const cut=new THREE.Plane(new THREE.Vector3(0,0,-1),24.28-originFeet.z).applyMatrix4(matrix);
  assert.ok(Math.abs(cut.distanceToPoint(scenePoint))<1e-9);assert.ok(cut.distanceToPoint(next)<0);
  assert.ok(matrix.determinant()>0,'registration must not mirror the model');
});
