import test from 'node:test';import assert from 'node:assert/strict';import{prepareIndoorPresentation}from'../lib/reviter/indoor-presentation.ts';import{nativeWallPositionRepairedWalls,nativeWallPositionRepairedPlanWalls}from'../lib/reviter/native-wall-position-repairs.ts';import{nativeDoorBoundaryClosureFootprints}from'../lib/reviter/native-door-boundary-closures.ts';import type{IndoorDataset}from'../lib/reviter/indoor-contract.ts';
const sha='a'.repeat(64);const ring=(x0:number,y0:number,x1:number,y1:number):[number,number][]=>[[x0,y0],[x1,y0],[x1,y1],[x0,y1]];
function incompletePrepass(){const d={source:{modelSha256:sha},nativeLevels:[{id:1,elevationFeet:0}],records:[],walls:[{levelId:1,nativeElementId:20,kind:'wall',ringsFeet:[ring(-1,0,.1,1)]},{levelId:1,nativeElementId:21,kind:'wall',ringsFeet:[ring(2,0,3,1)]}],doors:[{id:'door:1:10',nativeElementId:10,levelId:1,pointFeet:[1,.5],normalFeet:[0,1],footprintFeet:ring(0,0,1.9,1),roomKeys:['a','b'],state:'connected'}],edges:[],nativeDoorBoundaryClosures:{version:1,sourceModelSha256:sha,doors:[{levelId:1,id:'closure:10',nativeElementId:10,originalDoor:{pointFeet:[1,.5],normalFeet:[0,1],footprintFeet:ring(0,0,1.9,1),roomKeys:['a','b']},footprintFeet:ring(0,0,2.0002,1),jambEvidence:[{nativeElementId:20,ringsFeet:[ring(-1,0,.1,1)]},{nativeElementId:21,ringsFeet:[ring(2,0,3,1)]}],evidenceSha256:sha,notes:'Two real native jambs; disposable closure, retain physical portal.'}]}};return d as unknown as IndoorDataset;}
test('routing prepass keeps physical doors and skips selection closures until complete floor/portal proof exists',()=>{const d=incompletePrepass(),before=JSON.stringify(d);assert.doesNotThrow(()=>prepareIndoorPresentation(d,[],undefined,{purpose:'routing-prepass'}));assert.equal(JSON.stringify(d),before);assert.throws(()=>prepareIndoorPresentation(d,[]),/floor|portal/);assert.throws(()=>nativeDoorBoundaryClosureFootprints(d,1),/floor|portal/);});
test('native position prepass binds original/support geometry while final full floor guard remains mandatory',()=>{const d=incompletePrepass();d.nativeDoorBoundaryClosures=undefined;d.doors=[];const original=[ring(0,1.002,10,1.302)],corrected=[ring(0,.9998,10,1.2998)],support=[ring(0,0,10,1)];d.walls=[{levelId:1,nativeElementId:20,ringsFeet:original},{levelId:1,nativeElementId:21,ringsFeet:support}];d.nativeWallPositionRepairs={version:1,sourceModelSha256:sha,walls:[{id:'normal',levelId:1,nativeElementId:20,originalRingsFeet:original,ringsFeet:corrected,supportEvidence:{nativeElementId:21,ringsFeet:support},evidenceSha256:sha,notes:'Whole native wall normal translation'}]};const walls=nativeWallPositionRepairedWalls(d,{deferPhysicalChecks:true});assert.deepEqual(walls[0]!.ringsFeet,corrected);assert.throws(()=>nativeWallPositionRepairedWalls({...d,walls}),/unsupported/);d.walls[1]!.ringsFeet=[ring(0,0,9,1)];assert.throws(()=>nativeWallPositionRepairedWalls(d,{deferPhysicalChecks:true}),/stale/);});

test('plan projection preserves both retained doorway host parts while translating only a checked complete wall',()=>{
 const d=incompletePrepass();const first=ring(0,0,2,1),second=ring(4,0,6,1),original=ring(0,3,10,3.3),corrected=ring(0,2.998,10,3.298);
 d.walls=[{levelId:1,nativeElementId:10,kind:'wall',ringsFeet:[first]},{levelId:1,nativeElementId:10,kind:'wall',ringsFeet:[second]},{levelId:1,nativeElementId:20,kind:'wall',ringsFeet:[corrected]}];
 const input=[{elementId:10,polygon:first},{elementId:10,polygon:second},{elementId:20,polygon:original}],before=JSON.stringify(input);
 assert.deepEqual(nativeWallPositionRepairedPlanWalls(input,d,1),input);
 d.nativeWallPositionRepairs={version:1,sourceModelSha256:sha,walls:[{id:'position',levelId:1,nativeElementId:20,originalRingsFeet:[original],ringsFeet:[corrected],supportEvidence:{nativeElementId:21,ringsFeet:[ring(0,1.99,10,2.998)]},evidenceSha256:sha,notes:'Previously validated complete translated wall.'}]};
 const plan=nativeWallPositionRepairedPlanWalls(input,d,1);assert.deepEqual(plan.map(w=>w.polygon),[first,second,corrected]);assert.equal(JSON.stringify(input),before);
 d.walls.push({levelId:1,nativeElementId:20,kind:'wall',ringsFeet:[ring(0,5,10,6)]});assert.throws(()=>nativeWallPositionRepairedPlanWalls(input,d,1),/one complete/);
});
