import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
const expect = (actual: unknown) => ({ toEqual: (expected: unknown) => assert.deepEqual(actual, expected), toThrow: () => assert.throws(actual as () => unknown) });
import type { IndoorDataset } from '../lib/reviter/indoor-contract.ts';
import { closedBoundaryDoors, nativeDoorBoundaryClosureFootprints, validateNativeDoorBoundaryClosureBinding, type NativeDoorBoundaryClosures } from '../lib/reviter/native-door-boundary-closures.ts';
const model = 'a'.repeat(64);
const ring = (x0:number,y0:number,x1:number,y1:number):[number,number][] => [[x0,y0],[x1,y0],[x1,y1],[x0,y1]];
function fixture() {
 const door={id:'door:1:10',nativeElementId:10,levelId:1,pointFeet:[1,.5],normalFeet:[0,1],footprintFeet:ring(0,0,1.9,1),roomKeys:['a','b'],state:'connected'};
 const walls=[{levelId:1,nativeElementId:20,kind:'wall',approximate:false,ringsFeet:[ring(-1,0,.1,1)]},{levelId:1,nativeElementId:21,kind:'wall',approximate:false,ringsFeet:[ring(2,0,3,1)]}];
 const data={source:{modelSha256:model},nativeLevels:[{id:1,elevationFeet:0}],walkingSupport:{version:1,sourceModelSha256:model,floors:[{nativeElementId:30,elevationFeet:0,ringsFeet:[ring(-4,-4,4,4)]}]},records:[],walls,doors:[door],edges:[{id:door.id,enabled:true,kind:'door',nativeElementId:10,roomKeys:door.roomKeys}],graph:{unchanged:true}} as unknown as IndoorDataset;
 const value:NativeDoorBoundaryClosures={version:1,sourceModelSha256:model,doors:[{id:'closure:10',levelId:1,nativeElementId:10,originalDoor:{pointFeet:[1,.5],normalFeet:[0,1],footprintFeet:ring(0,0,1.9,1),roomKeys:['a','b']},footprintFeet:ring(0,0,2.0002,1),jambEvidence:walls.map(w=>({nativeElementId:w.nativeElementId,ringsFeet:structuredClone(w.ringsFeet)})),evidenceSha256:'b'.repeat(64),notes:'Measured native jamb correction.'}]};
 return{data,value};
}
describe('source-bound native doorway display closure',()=>{
 it('returns only disposable tangent corrections and retains physical doorway and portal',()=>{const{data,value}=fixture(),before=structuredClone(data);const out=closedBoundaryDoors(data,1,value);expect(out[0]!.footprintFeet).toEqual(value.doors[0]!.footprintFeet);expect(data).toEqual(before);expect(out[0]!.normalFeet).toEqual(data.doors![0]!.normalFeet);expect(out[0]!.pointFeet).toEqual(data.doors![0]!.pointFeet);const saved={...data,nativeDoorBoundaryClosures:value};expect(nativeDoorBoundaryClosureFootprints(saved,1)).toEqual([{nativeElementId:10,footprintFeet:value.doors[0]!.footprintFeet}]);validateNativeDoorBoundaryClosureBinding({nativeDoorBoundaryClosures:value},saved);expect(()=>validateNativeDoorBoundaryClosureBinding({},saved)).toThrow();});
 it('rejects stale source, door, jamb, missing portal, duplicate door and depth/width changes',()=>{for(const edit of [(v:NativeDoorBoundaryClosures)=>v.sourceModelSha256='c'.repeat(64),(v:NativeDoorBoundaryClosures)=>v.doors[0]!.originalDoor.pointFeet[0]+=.01,(v:NativeDoorBoundaryClosures)=>v.doors[0]!.jambEvidence[0]!.ringsFeet[0]![0]![0]+=.01,(v:NativeDoorBoundaryClosures)=>v.doors.push(structuredClone(v.doors[0]!)),(v:NativeDoorBoundaryClosures)=>v.doors[0]!.footprintFeet=ring(0,0,2.1,1),(v:NativeDoorBoundaryClosures)=>v.doors[0]!.footprintFeet=ring(0,-.01,2.0002,1)]){const{data,value}=fixture();edit(value);expect(()=>closedBoundaryDoors(data,1,value)).toThrow();}const{data,value}=fixture();data.edges[0]!.enabled=false;expect(()=>closedBoundaryDoors(data,1,value)).toThrow();});
 it('protects slab holes, floor openings, foreign columns, fixtures and finite jamb contact',()=>{for(const edit of [(d:IndoorDataset)=>d.walkingSupport!.floors[0]!.ringsFeet.push(ring(1.95,.2,1.99,.8)),(d:IndoorDataset)=>d.records.push({levelId:1,properties:{floorOpeningsFeet:[ring(1.95,.2,1.99,.8)]}} as any),(d:IndoorDataset)=>d.walls.push({levelId:1,nativeElementId:99,kind:'column',approximate:false,ringsFeet:[ring(1.95,.2,1.99,.8)]}),(d:IndoorDataset)=>d.circulationGeometry={version:1,sourceModelSha256:model,sourceGeometryKey:'native',cells:[],fixtures:[{id:'fixture',nativeElementId:99,levelIds:[1],elevationFeet:0,heightFeet:1,ringsFeet:[ring(1.95,.2,1.99,.8)]}]}]){const{data,value}=fixture();edit(data);expect(()=>closedBoundaryDoors(data,1,value)).toThrow();}const{data,value}=fixture();data.walls[1]!.ringsFeet=[ring(2,.95,3,1.2)];value.doors[0]!.jambEvidence[1]!.ringsFeet=data.walls[1]!.ringsFeet;expect(()=>closedBoundaryDoors(data,1,value)).toThrow();});
});

describe('unmatched doorway selection barrier',()=>{
 function unmatched(){const{data,value}=fixture();data.doors![0]!.state='unmatched';data.doors![0]!.roomKeys=['a'];data.edges=[];value.doors[0]!.selectionBarrierOnly=true;value.doors[0]!.originalDoor.roomKeys=['a'];return{data,value};}
 it('closes exact supported jambs without introducing a route or altering original unmatched metadata',()=>{const{data,value}=unmatched(),before=structuredClone(data);const out=closedBoundaryDoors(data,1,value);assert.deepEqual(out[0]!.footprintFeet,value.doors[0]!.footprintFeet);assert.equal(out[0]!.state,'unmatched');assert.deepEqual(out[0]!.roomKeys,['a']);assert.deepEqual(data,before);assert.deepEqual(data.edges,[]);});
 it('rejects enabled portals, connected state, unknown sides and physically unsupported unmatched thresholds',()=>{for(const edit of [(d:IndoorDataset,v:NativeDoorBoundaryClosures)=>d.edges.push({id:d.doors![0]!.id,enabled:true,kind:'door',nativeElementId:10,roomKeys:['a','b']} as any),(d:IndoorDataset)=>d.edges.push({id:'alternate-physical-portal',enabled:true,kind:'door',nativeElementId:10,roomKeys:['a','b']} as any),(d:IndoorDataset)=>d.doors![0]!.state='connected',(_d:IndoorDataset,v:NativeDoorBoundaryClosures)=>v.doors[0]!.originalDoor.roomKeys=[],(_d:IndoorDataset,v:NativeDoorBoundaryClosures)=>{delete v.doors[0]!.selectionBarrierOnly;},(d:IndoorDataset)=>d.walkingSupport!.floors[0]!.ringsFeet.push(ring(1.95,.2,1.99,.8)),(d:IndoorDataset)=>d.walls.push({levelId:1,nativeElementId:99,kind:'column',approximate:false,ringsFeet:[ring(1.95,.2,1.99,.8)]})]){const{data,value}=unmatched();edit(data,value);assert.throws(()=>closedBoundaryDoors(data,1,value));}});
});

describe('explicit measured supported-doorway exception',()=>{
 it('keeps the default bound and permits only an explicit bounded full-jamb correction with the original supported portal',()=>{const{data,value}=fixture();data.walls[1]!.ringsFeet=[ring(2.09,0,3,1)];value.doors[0]!.jambEvidence[1]!.ringsFeet=structuredClone(data.walls[1]!.ringsFeet);value.doors[0]!.footprintFeet=ring(0,0,2.0902,1);assert.throws(()=>closedBoundaryDoors(data,1,value));value.doors[0]!.measuredTangentLimitFeet=.2;const before=structuredClone(data);assert.deepEqual(closedBoundaryDoors(data,1,value)[0]!.footprintFeet,value.doors[0]!.footprintFeet);assert.deepEqual(data,before);data.edges[0]!.enabled=false;assert.throws(()=>closedBoundaryDoors(data,1,value));});
 it('rejects excess limits and use on unmatched or physically unsupported doorways',()=>{for(const edit of [(d:IndoorDataset,v:NativeDoorBoundaryClosures)=>v.doors[0]!.measuredTangentLimitFeet=.201,(d:IndoorDataset,v:NativeDoorBoundaryClosures)=>{v.doors[0]!.selectionBarrierOnly=true;v.doors[0]!.originalDoor.roomKeys=['a'];d.doors![0]!.state='unmatched';d.doors![0]!.roomKeys=['a'];d.edges=[];},(d:IndoorDataset)=>d.walkingSupport!.floors[0]!.ringsFeet.push(ring(1.95,.2,1.99,.8))]){const{data,value}=fixture();value.doors[0]!.measuredTangentLimitFeet=.2;edit(data,value);assert.throws(()=>closedBoundaryDoors(data,1,value));}});
});
