import test from'node:test';import assert from'node:assert/strict';import{validateNativeSourceStairWidth,type NativeSourceStairReceipt,type NativeSourceStairFloor}from'../lib/reviter/native-source-stair-width.ts';
const ring=(a:number,b:number,w=3):[number,number][]=>[[a,0],[b,0],[b,w],[a,w]];
const fixture=()=>{const floors:NativeSourceStairFloor[]=[{nativeElementId:100,elevationFeet:0,ringsFeet:[ring(0,.5)]},{nativeElementId:101,elevationFeet:1.5,ringsFeet:[ring(2.5,3.5)]}];const r:NativeSourceStairReceipt={version:1,sourceModelSha256:'a'.repeat(64),nativeStairId:10,nativeRunIds:[11],levelIds:[1,2],nativeFloorElementIds:[100,101],widthFeet:2,pointsFeet:[[.4,1.5,0],[1,1.5,.5],[2,1.5,1],[2.6,1.5,1.5]],treads:[{runElementId:11,elevationFeet:.5,ringFeet:ring(.5,1.5)},{runElementId:11,elevationFeet:1,ringFeet:ring(1.5,2.5)}],landings:[],terminalCaps:[{pointFeet:[.4,1.5,0],capFeet:[[.5,0,.5],[.5,3,.5]],levelId:1,nativeFloorElementId:100,originalRunElementId:11},{pointFeet:[2.6,1.5,1.5],capFeet:[[2.5,0,1],[2.5,3,1]],levelId:2,nativeFloorElementId:101,originalRunElementId:11}]};return{r,floors}};
test('original adjacent-height walking tops support whole two-foot flight and both named slab caps',()=>{const{r,floors}=fixture();assert.equal(validateNativeSourceStairWidth(r,floors),true)});
test('a real narrow gap between original treads is not bridged',()=>{const{r,floors}=fixture();r.treads[1]!.ringFeet=ring(1.501,2.5);assert.equal(validateNativeSourceStairWidth(r,floors),false)});
test('source floor holes and narrow treads remain excluded',()=>{const{r,floors}=fixture();floors[1]!.ringsFeet.push([[2.55,.4],[2.55,2.6],[2.65,2.6],[2.65,.4]]);assert.equal(validateNativeSourceStairWidth(r,floors),false);const q=fixture();q.r.treads[0]!.ringFeet=ring(.5,1.5,1.99);assert.equal(validateNativeSourceStairWidth(q.r,q.floors),false)});
test('skipping the original walking tread chain or using a wrong named slab is rejected',()=>{const{r,floors}=fixture();r.pointsFeet.splice(1,2);assert.equal(validateNativeSourceStairWidth(r,floors),false);const q=fixture();q.r.nativeFloorElementIds[1]=999;assert.equal(validateNativeSourceStairWidth(q.r,q.floors),false)});
import{prepareNativeSourceStairReceipts}from'../lib/reviter/native-source-stair-receipts.ts';
test('constructor independently binds exact original owned typed tread profiles; prepared display tampering cannot authorize a flight',()=>{const{r,floors}=fixture();const model={levels:[{levelId:1,elevation:0},{levelId:2,elevation:1.5}],elementBounds:[...floors.map(f=>({elementId:f.nativeElementId,categoryId:-2000032,boundsFeet:{min:{x:0,y:0,z:f.elevationFeet-.1},max:{x:3.5,y:3,z:f.elevationFeet}},loops:f.ringsFeet.map(h=>h.map(p=>[...p,f.elevationFeet]))})),{elementId:11,boundsFeet:{min:{z:0},max:{z:1.5}},stairTreads:r.treads.map(t=>t.ringFeet.map(p=>[...p,t.elevationFeet]))}],nativeStairAssemblies:[{stairElementId:10,runAndLandingIds:[11]}]};const data={source:{modelSha256:r.sourceModelSha256},nativePhysicalLevels:{displayAliases:[{nativeLevelId:2}]},stairDisplay:{sourceFlights:[{stairElementId:10,levelIds:[1,2],treads:r.treads,runs:[{runElementId:11,bottomElevationFeet:0,topElevationFeet:1.5}],landings:[]}]}};assert.equal(prepareNativeSourceStairReceipts(model as never,data as never).receipts.length,1);const before=JSON.stringify(model);data.stairDisplay.sourceFlights[0]!.treads[0]!.ringFeet[0]![0]+=.001;assert.equal(prepareNativeSourceStairReceipts(model as never,data as never).receipts.length,0);assert.equal(JSON.stringify(model),before)});

test('ordinary primary-floor source flights are eligible proposals without fictional fractional aliases',()=>{
 const{r,floors}=fixture();const model={levels:[{levelId:1,elevation:0},{levelId:2,elevation:1.5}],elementBounds:[...floors.map(f=>({elementId:f.nativeElementId,categoryId:-2000032,boundsFeet:{min:{x:0,y:0,z:f.elevationFeet-.1},max:{x:3.5,y:3,z:f.elevationFeet}},loops:f.ringsFeet.map(h=>h.map(p=>[...p,f.elevationFeet]))})),{elementId:11,boundsFeet:{min:{z:0},max:{z:1.5}},stairTreads:r.treads.map(t=>t.ringFeet.map(p=>[...p,t.elevationFeet]))}],nativeStairAssemblies:[{stairElementId:10,runAndLandingIds:[11]}]};
 const data={source:{modelSha256:r.sourceModelSha256},stairDisplay:{sourceFlights:[{stairElementId:10,levelIds:[1,2],treads:r.treads,runs:[{runElementId:11,bottomElevationFeet:0,topElevationFeet:1.5}],landings:[]}]}};
 const proposed=prepareNativeSourceStairReceipts(model as never,data as never);assert.equal(proposed.receipts.length,1);assert.equal(proposed.foreignMaterialOrEnclosureApproved,false);assert.equal(proposed.walkingBodyApproved,false);assert.equal('walkingBody' in proposed.receipts[0]!,false);
 (data.stairDisplay.sourceFlights[0] as any).context='tiered-seating';assert.equal(prepareNativeSourceStairReceipts(model as never,data as never).receipts.length,0);
});
