import {test}from'node:test';import assert from'node:assert/strict';import {withReviewedDoorApertures,applyReviewedDoorWallCuts,reviewedDoorOpening,type ReviewedDoorApertures}from'../lib/reviter/reviewed-door-apertures.ts';
const sha='a'.repeat(64),quad=(x0:number,y0:number,x1:number,y1:number)=>[[x0,y0],[x1,y0],[x1,y1],[x0,y1]]as[number,number][],box=(y0:number,y1:number,z0:number,z1:number)=>[...quad(-.25,y0,.25,y1).map(p=>[...p,z0]),...quad(-.25,y0,.25,y1).map(p=>[...p,z1])];
function fixture(){const frames=[3,4,5,6].map((elementId,i)=>({elementId,categoryId:-2000171,renderGeometryProvenance:'native',orientedBox:[box(2,4,7,7.2),box(2,4,-.2,0),box(1.8,2,-.2,7.2),box(4,4.2,-.2,7.2)][i]}));const model:any={elementBounds:[{elementId:2,categoryId:-2000023,orientedBox:box(2,4,0,7)},...frames],nativeHostRelations:[2,...frames.map(f=>f.elementId)].map(elementId=>({elementId,hostId:10,evidence:'persisted'}))};const walls=[{elementId:1,polygon:quad(-1,0,1,6),approximate:false},{elementId:7,polygon:quad(2,0,3,6),approximate:false}];const geometry={walls,columns:[],floors:[ [quad(-4,-4,4,8)] ],cutElevation:4};const value:ReviewedDoorApertures={version:1,sourceModelSha256:sha,patches:[{id:'reviewed-door',levelId:1,nativeDoorId:2,normalFeet:[1,0],apertureFeet:quad(-1,2,1,4),wallEvidence:[{nativeElementId:1,partsFeet:[walls[0].polygon]}],frameEvidence:frames.map(f=>({nativeElementId:f.elementId,orientedBox:f.orientedBox})),notes:'Explicit review of duplicate host envelope, keep measured jambs.'}]};return{model,value:structuredClone(value),geometry,walls};}
test('explicit model-bound aperture cuts only checked hosts and keeps source geometry intact',()=>{const f=fixture(),before=JSON.stringify(f.model),m=withReviewedDoorApertures(f.model,f.value,sha,()=>f.geometry);assert.notEqual(m,f.model);assert.equal(JSON.stringify(f.model),before);const result=applyReviewedDoorWallCuts(m,1,f.walls);assert.equal(result.filter(w=>w.elementId===1).length,2);assert.deepEqual(result.find(w=>w.elementId===7),f.walls[1]);assert.equal(reviewedDoorOpening(f.model,1,2),undefined);assert.equal(reviewedDoorOpening(m,2,2),undefined);assert.equal(reviewedDoorOpening(m,1,2)?.nativeDoorId,2);});
test('stale native frames, mismatched originals, measured width, unsupported floor and columns veto correction',()=>{for(const change of [(f:any)=>f.model.elementBounds[1].renderGeometryProvenance='reconstructed',(f:any)=>f.model.elementBounds[1].orientedBox[0][0]+=1,(f:any)=>f.geometry.walls[0].polygon[0][0]-=.1,(f:any)=>f.value.patches[0].apertureFeet[0][1]=1.9,(f:any)=>f.geometry.floors=[[quad(-4,-4,4,8),quad(-.1,2.2,.1,3.8)]],(f:any)=>f.geometry.columns=[{polygon:quad(-.1,2.2,.1,3.8)}]]){const f=fixture();change(f);assert.throws(()=>withReviewedDoorApertures(f.model,f.value,sha,()=>f.geometry));}const f=fixture();assert.throws(()=>withReviewedDoorApertures(f.model,f.value,'b'.repeat(64),()=>f.geometry));});
function basicFixture(){const f=fixture(),host=quad(-.2,0,.2,6),overlap=quad(-.25,0,.15,6);f.model.elementBounds=[{elementId:2,categoryId:-2000023,orientedBox:box(2,4,0,7)},{elementId:10,categoryId:-2000011},{elementId:11,categoryId:-2000011}];const b=f.model.elementBounds[0].orientedBox;b.forEach((p:number[])=>p[0]=p[0]<0?-.2:.2);f.model.nativeHostRelations=[{elementId:2,hostId:10,evidence:'persisted'}];f.geometry.walls=[{elementId:10,polygon:host,approximate:false},{elementId:11,polygon:overlap,approximate:false}];Object.assign(f.value.patches[0],{kind:'basic-wall-overlap',doorEvidence:{hostId:10,orientedBox:structuredClone(b)},frameEvidence:[],apertureFeet:quad(-.25,2,.2,4),wallEvidence:f.geometry.walls.map(w=>({nativeElementId:w.elementId,partsFeet:[w.polygon]}))});return f;}
test('explicit basic-wall overlap follows exact physical width and host depth without mutating the source',()=>{const f=basicFixture(),before=JSON.stringify(f.model),m=withReviewedDoorApertures(f.model,f.value,sha,()=>f.geometry);assert.equal(JSON.stringify(f.model),before);const cut=applyReviewedDoorWallCuts(m,1,f.geometry.walls);assert.equal(cut.length,4);assert.equal(reviewedDoorOpening(m,1,2)?.kind,'basic-wall-overlap');});
test('basic-wall correction rejects stale host, changed width, unrelated partitions, excessive depth and floor holes',()=>{for(const edit of[(f:any)=>f.geometry.walls[1].approximate=true,(f:any)=>f.model.elementBounds[2].categoryId=-2000171,(f:any)=>f.model.nativeHostRelations[0].hostId=99,(f:any)=>f.model.elementBounds[0].orientedBox[0][0]-=.01,(f:any)=>f.value.patches[0].apertureFeet[0][1]-=.01,(f:any)=>{f.geometry.walls[1].polygon=quad(-.5,0,-.3,6);f.value.patches[0].wallEvidence[1].partsFeet=[f.geometry.walls[1].polygon]},(f:any)=>{f.geometry.walls[1].polygon=quad(-.4,0,.15,6);f.value.patches[0].wallEvidence[1].partsFeet=[f.geometry.walls[1].polygon]},(f:any)=>f.geometry.floors=[[quad(-4,-4,4,8),quad(-.1,2.2,.1,3.8)]]]){const f=basicFixture();edit(f);assert.throws(()=>withReviewedDoorApertures(f.model,f.value,sha,()=>f.geometry));}});
function singleBasicFixture(){
 const f=fixture(),host=quad(-.2,0,.2,12),physical=box(2,9,0,7),normal:[number,number]=[1,0],footprint=quad(-.25,2,.25,9);
 f.model.elementBounds=[{elementId:2,categoryId:-2000023,orientedBox:physical},{elementId:10,categoryId:-2000011,wallKind:'basic',renderGeometryProvenance:'native',solid:{start:{x:0,y:0},end:{x:0,y:12},thickness:.4}}];
 f.model.nativeHostRelations=[{elementId:2,hostId:10,evidence:'persisted'}];f.geometry.walls=[{elementId:10,polygon:host,approximate:false}];f.geometry.floors=[[quad(-4,-4,4,14)]];
 Object.assign(f.value.patches[0],{kind:'basic-host-missing-opening',normalFeet:normal,doorEvidence:{hostId:10,orientedBox:structuredClone(physical)},preparedDoorEvidence:{pointFeet:[0,5.5],normalFeet:normal,footprintFeet:structuredClone(footprint),roomKeys:['vestibule','alcove'],evidenceSha256:'b'.repeat(64)},frameEvidence:[],apertureFeet:footprint,wallEvidence:[{nativeElementId:10,partsFeet:[host]}]});return f;
}
test('source-bound single basic host restores only an existing measured double-door opening',()=>{
 const f=singleBasicFixture(),before=JSON.stringify(f.model),m=withReviewedDoorApertures(f.model,f.value,sha,()=>f.geometry);
 assert.equal(JSON.stringify(f.model),before);assert.equal(applyReviewedDoorWallCuts(m,1,f.geometry.walls).length,2);
 assert.equal(reviewedDoorOpening(m,1,2)?.kind,'basic-host-missing-opening');
});
test('single basic host rejects stale native evidence, arbitrary width/depth, foreign material and protected floor',()=>{
 for(const edit of[(f:any)=>f.model.nativeHostRelations[0].hostId=99,(f:any)=>f.model.elementBounds[1].wallKind='curtain',(f:any)=>f.model.elementBounds[1].renderGeometryProvenance='reconstructed',(f:any)=>f.model.elementBounds[0].orientedBox[0][1]+=.01,(f:any)=>f.geometry.walls[0].polygon[0][1]+=.01,(f:any)=>f.value.patches[0].apertureFeet[0][1]-=.1,(f:any)=>f.value.patches[0].apertureFeet[0][0]-=.1,(f:any)=>f.value.patches[0].preparedDoorEvidence.pointFeet[0]+=.01,(f:any)=>f.value.patches[0].preparedDoorEvidence.footprintFeet[0][1]-=.1,(f:any)=>f.geometry.floors=[[quad(-4,-4,4,14),quad(-.1,4,.1,5)]],(f:any)=>f.geometry.columns=[{polygon:quad(-.1,4,.1,5)}],(f:any)=>f.geometry.walls.push({elementId:50,polygon:quad(-.1,4,.1,5),approximate:false}),(f:any)=>f.geometry.walls[0].approximate=true]){
  const f=singleBasicFixture();edit(f);assert.throws(()=>withReviewedDoorApertures(f.model,f.value,sha,()=>f.geometry));
 }
});
