/** Run the same checks as Floors → Building directory for every supplied floor.
 * node --experimental-strip-types scripts/audit-room-directory.ts rooms.json model-cache.json catalog.json output-directory
 * The local cache contains conversion levels, elementBounds, nativeAssociatedLevelRelations,
 * and optionally nativeHostRelations/nativeStairAssemblies for door depth and stair evidence.
 */
import fs from "node:fs";
import path from "node:path";
import type { ConvertResult } from "../lib/reviter/types.ts";
import { auditDirectoryFloor } from "../lib/reviter/directory-audit.ts";
import { directoryDoors, directoryDoorReviews, directoryStairs } from "../lib/reviter/directory-navigation.ts";
import { containsDirectoryRoomPoint, hallwayRouteComponents, isHallway, parseRoomDirectory, roomBuilding, type DirectoryRoom, type RoomPoint } from "../lib/reviter/room-directory.ts";
const [roomFile,modelFile,catalogFile,output]=process.argv.slice(2);
if(!roomFile || !modelFile || !catalogFile || !output)throw new Error("Provide rooms, a local conversion cache, survey catalog and output directory.");
const data=parseRoomDirectory(fs.readFileSync(roomFile,"utf8")),model=JSON.parse(fs.readFileSync(modelFile,"utf8")) as ConvertResult;
const catalog=JSON.parse(fs.readFileSync(catalogFile,"utf8")) as {sheets:{name:string;file:string}[]};
fs.mkdirSync(output,{recursive:true});
const rooms=data.annotations.filter(r=>r.status!=="deleted");
const groups=new Map<string,DirectoryRoom[]>();for(const r of rooms){const key=`${roomBuilding(r)}:${r.levelId}`;groups.set(key,[...groups.get(key)??[],r]);}
const doors=new Map([...new Set(rooms.map(r=>r.levelId))].map(id=>[id,directoryDoors(model,id)]));
const stairs=directoryStairs(model,rooms,data.navigation?.stairLinks);
const escape=(value:unknown)=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]!));
const polygonPath=(loops:RoomPoint[][])=>loops.map(l=>l.map((p,i)=>`${i?"L":"M"}${p[0]},${-p[1]}`).join(" ")+"Z").join(" ");
const floors=[];
for(const [key,group] of [...groups].sort(([a],[b])=>a.localeCompare(b,undefined,{numeric:true}))){
  const levelId=group[0]!.levelId,reviews=directoryDoorReviews(group,doors.get(levelId)!,data.navigation?.doorLinks),portals=reviews.flatMap(d=>d.portal?[d.portal]:[]);
  const audit=auditDirectoryFloor(group,portals,reviews,stairs,data.boundaryReference),components=hallwayRouteComponents(group,portals);
  const reference=data.boundaryReference?.sections.filter(s=>s.levelId===levelId&&group.some(r=>r.dwg?.sectionId===s.sectionId))??[];
  const unique=group.filter((r,i)=>!r.circulationGroup || group.findIndex(o=>o.circulationGroup===r.circulationGroup)===i),flagged=new Set(audit.issues.map(i=>i.roomKey));
  const points=group.flatMap(r=>r.polygonFeet),x0=Math.min(...points.map(p=>p[0]))-5,y0=Math.min(...points.map(p=>p[1]))-5,x1=Math.max(...points.map(p=>p[0]))+5,y1=Math.max(...points.map(p=>p[1]))+5;
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${x0} ${-y1} ${x1-x0} ${y1-y0}" style="background:white">`+unique.map(r=>`<path d="${polygonPath([r.polygonFeet,...r.holesFeet??[]])}" fill="${isHallway(r)?"#d5efad":"#bce8e2"}" fill-rule="evenodd" stroke="${flagged.has(r.key)?"#c96a21":"#237177"}" stroke-width=".14"><title>${escape(r.number)} ${escape(r.name)}</title></path>`).join("")+`<g fill="none" stroke="#303c4e" stroke-width=".11">`+reference.flatMap(s=>s.wallSegments).map(([a,b])=>`<path d="M${a[0]},${-a[1]} L${b[0]},${-b[1]}"/>`).join("")+`</g>`+group.map(r=>`<circle cx="${r.labelPointFeet[0]}" cy="${-r.labelPointFeet[1]}" r=".32" fill="${containsDirectoryRoomPoint(r.labelPointFeet,r)?"#16475f":"#d51d36"}"><title>${escape(r.number)} ${escape(r.name)}</title></circle>`).join("")+"</svg>";
  const svgFile=`floor-${key.replace(":","-")}.svg`;fs.writeFileSync(path.join(output,svgFile),svg);
  const floor={...audit,key,levelName:model.levels.find(l=>l.levelId===levelId)?.name,sourceSheets:[...new Set(group.map(r=>r.dwg?.sectionId).filter(Boolean))],hallwayComponents:components.map(c=>c.map(k=>group.find(r=>r.key===k)?.number??k)),labelOutside:audit.issues.filter(i=>i.kind==="anchor").length,issues:audit.issues.map(i=>({...i,room:group.find(r=>r.key===i.roomKey)?.number??i.roomKey})),svgFile};
  floors.push(floor);console.log(key,`${audit.routesPassed}/${audit.destinations} destination routes; ${audit.networks} route networks; ${audit.issues.length} review flags`);
}
const annotatedBuildings=[...new Set(rooms.map(roomBuilding))].sort(),surveyBuildings=[...new Set(catalog.sheets.map(s=>s.name.match(/^\d+/)?.[0]).filter((s):s is string=>!!s))].sort();
const sheets=new Set(rooms.map(r=>r.dwg?.sectionId?.replace(/ #\d+$/, "")));
const surveySheetsWithoutAnnotations=catalog.sheets.filter(s=>/^\d/.test(s.name)&&!sheets.has(s.name));
const summary={floorCombinations:floors.length,destinationCount:floors.reduce((n,f)=>n+f.destinations,0),destinationRoutesPassed:floors.reduce((n,f)=>n+f.routesPassed,0),destinationRoutesFailed:floors.reduce((n,f)=>n+f.destinations-f.routesPassed,0),splitHallwayFloors:floors.filter(f=>f.networks>1).length,anchorsOutside:floors.reduce((n,f)=>n+f.labelOutside,0),stairConnections:stairs.length};
const report={version:1,createdAt:new Date().toISOString(),engine:"live-building-directory",sourceFile:path.resolve(roomFile),annotationCount:rooms.length,annotatedBuildings,surveyBuildings,unannotatedBuildings:surveyBuildings.filter(b=>!annotatedBuildings.includes(b)),surveySheetsWithoutAnnotations,summary,stairs,floors,scope:"Every imported room is checked with the same routines as the live building directory. Routes use recovered openings and current room outlines; field conditions and access restrictions are not independently verified."};
fs.writeFileSync(path.join(output,"audit.json"),JSON.stringify(report,null,2));
const csv=(value:unknown)=>`"${String(value??"").replace(/"/g,'""')}"`;
fs.writeFileSync(path.join(output,"room-issues.csv"),[["Building","Model level","Room","Issue","Detail"].map(csv).join(","),...floors.flatMap(f=>f.issues.map(i=>[f.building,f.levelId,i.room,i.kind,i.message].map(csv).join(",")))].join("\n"));
const rows=floors.map(f=>`<tr><td><a href="#${f.key}">${escape(f.building)}</a></td><td>${escape(f.levelName)}</td><td>${f.roomCount}</td><td>${f.networks}</td><td>${f.routesPassed}/${f.destinations}</td><td>${f.stairLinks}</td><td>${f.issues.length}</td></tr>`).join("");
const cards=floors.map(f=>`<section id="${f.key}"><h2>Building ${escape(f.building)} · ${escape(f.levelName)} · level ${f.levelId}</h2><p>${escape(f.sourceSheets.join(", "))}</p><p>${f.networks} hallway route networks · ${f.routesPassed}/${f.destinations} destination routes · ${f.connectedDoors} linked doors · ${f.stairLinks} stair connections</p><img loading="lazy" src="${f.svgFile}" alt="Boundary and surveyed wall overview"><details><summary>${f.issues.length} review flags</summary><table><thead><tr><th>Room</th><th>Issue</th><th>Evidence</th></tr></thead><tbody>${f.issues.map(i=>`<tr><td>${escape(i.room)}</td><td>${escape(i.kind)}</td><td>${escape(i.message)}</td></tr>`).join("")}</tbody></table></details></section>`).join("");
fs.writeFileSync(path.join(output,"index.html"),`<!doctype html><html lang="en"><meta charset="utf-8"><title>UNBC building and floor audit</title><style>body{font:15px system-ui;line-height:1.5;max-width:1200px;margin:40px auto;padding:0 24px;background:#f3f6f8;color:#152d40}table{border-collapse:collapse;width:100%;background:white}td,th{padding:8px;text-align:left;border-bottom:1px solid #dae0e4}section{background:white;margin:28px 0;padding:24px;border-radius:12px}img{width:100%;height:620px;object-fit:contain}a{color:#046977}</style><h1>UNBC building and floor audit</h1><p><strong>The checks, door review and staircase navigation are now in <a href="http://localhost:5173/">Floors → Building directory</a>.</strong></p><p>${escape(report.scope)}</p><p><strong>${annotatedBuildings.length} annotated buildings · ${floors.length} building floors · ${rooms.length} labels · ${stairs.length} matched staircase connections</strong></p><p>${summary.destinationRoutesPassed}/${summary.destinationCount} destination routes pass; ${summary.splitHallwayFloors} floors have separate route networks; ${summary.anchorsOutside} outside anchors.</p><p>Building 10, level 1487816 now has ${floors.find(f=>f.key==="10:1487816")?.networks} route networks and ${floors.find(f=>f.key==="10:1487816")?.routesPassed}/${floors.find(f=>f.key==="10:1487816")?.destinations} destination routes. The atrium/base survey registrations and the entrance vestibule have been corrected. Remaining gaps are listed below.</p><p>Survey-only buildings without room annotations: ${report.unannotatedBuildings.join(", ")}. ${surveySheetsWithoutAnnotations.length} survey sheets lack room coverage.</p><p><a href="room-issues.csv">Room issue CSV</a> · <a href="audit.json">Detailed audit JSON</a></p><p>Green: circulation. Teal: rooms. Orange: review flags. Dark lines: survey walls. Red dots: anchors outside the usable room. Hallway networks are tested with actual floor routes.</p><table><thead><tr><th>Building</th><th>Model floor</th><th>Labels</th><th>Route networks</th><th>Destination routes</th><th>Stair links</th><th>Flags</th></tr></thead><tbody>${rows}</tbody></table>${cards}</html>`);
console.log("Saved",path.resolve(output));
