/** Source-model correction inventory. No native RVT bytes or room outlines change. */
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {readProjectPackage} from '../lib/reviter/project-package.ts';
import {auditRoomBoundaries} from '../lib/reviter/room-boundary-audit.ts';
import {convertRvtBytes} from '../lib/reviter/convert.ts';
import type {ConvertResult} from '../lib/reviter/types.ts';
const args=process.argv.slice(2),option=(name:string)=>{const i=args.indexOf(name);return i<0?undefined:args[i+1]};
const input=option('--input'),out=option('--out');if(!input||!out)throw Error('Supply --input prepared.reviter.zip --out source-model-review.json [--native-cache model-bound-cache.json].');
const pkg=await readProjectPackage(new Uint8Array(await readFile(resolve(input))));if(!pkg.indoor)throw Error('Prepared indoor geometry is required.');
let model:ConvertResult;
if(option('--native-cache')){const cached=JSON.parse(await readFile(resolve(option('--native-cache')!),'utf8')) as {sourceModelSha256:string;nativeModel:ConvertResult};if(cached.sourceModelSha256!==pkg.manifest.model.sha256||cached.nativeModel?.fileName!==pkg.model.name)throw Error('Native audit cache does not match the exact source model.');model=cached.nativeModel;}
else{const result=convertRvtBytes(new Uint8Array(await pkg.model.arrayBuffer()),pkg.model.name,{});if(!result.ok)throw Error(result.error);model=result;}
const boundaries=auditRoomBoundaries(pkg.indoor,pkg.rooms.annotations),walls=model.elementBounds.filter(e=>e.categoryName==='Walls'||e.categoryId===-2000011);
const levels=new Map<number,number[]>();for(const relation of model.nativeAssociatedLevelRelations??[])levels.set(relation.elementId,[...levels.get(relation.elementId)??[],relation.levelId]);
const preparedWallLevels=new Map<number,number[]>();for(const wall of pkg.indoor.walls){if(wall.nativeElementId!==undefined)preparedWallLevels.set(wall.nativeElementId,[...new Set([...(preparedWallLevels.get(wall.nativeElementId)??[]),wall.levelId])]);}
const wallReview=walls.filter(e=>!levels.get(e.elementId)?.length || !(e.solid||e.solids?.length||e.arcs?.length||e.quads?.length)).map(e=>({nativeElementId:e.elementId,category:e.categoryName,type:e.typeName,wallKind:e.wallKind,nativeLevelIds:levels.get(e.elementId)??[],preparedCutLevelIds:preparedWallLevels.get(e.elementId)??[],boundsFeet:e.boundsFeet,parameters:e.parameters??[],reason:!levels.get(e.elementId)?.length?'native-floor-association-unresolved':e.wallKind==='curtain'?'curtain-parent-geometry-delegated':'native-wall-footprint-unverified',nextAction:!levels.get(e.elementId)?.length?(preparedWallLevels.get(e.elementId)?.length?'Exact native solid geometry is already included at the prepared floor cut elevations listed here. Preserve that geometry; only the semantic native level association remains undecoded.':'Inspect wall Base Constraint and phase in Revit; export its level association. Bounds height alone must not invent a floor connection.'):e.wallKind==='curtain'?'Audit native curtain panel/mullion child coverage before treating this parent as missing geometry; a curtain-wall aggregate normally has child bodies.':'Inspect/re-export the basic wall geometry in Revit. A tiny or bounds-only envelope does not prove its exact room-facing footprint or a missing partition.'}));
const semanticParameters=model.elementBounds.flatMap(e=>(e.parameters??[]).filter(p=>/room.?bounding|phase created|phase demolished/i.test([p.name,p.enumName].join(' '))).map(p=>({nativeElementId:e.elementId,...p})));
const records=new Map(pkg.indoor.records.map(r=>[r.key,r]));
const fallback=boundaries.rooms.filter(r=>r.status==='source-fallback');
const report={version:1,sourceModelSha256:pkg.manifest.model.sha256,sourceRoomsSha256:pkg.manifest.floors.sha256,
 ordinaryRoomFallbackCount:fallback.filter(r=>!records.get(r.roomKey)?.stair).length,stairAreaFallbackCount:fallback.filter(r=>records.get(r.roomKey)?.stair).length,
 semanticInventory:{status:'not-determined-from-geometry-decoder',decodedRoomBounds:model.elementBounds.filter(e=>/^(rooms?|spaces?)$/i.test(e.categoryName??'')).length,decodedPhaseOrRoomBoundingParameters:semanticParameters.length,
  limitation:'Zero decoded Room/phase/Room Bounding values does not establish that the source lacks Rooms or phases. Geometry recovery does not provide a complete non-geometric Revit element/parameter inventory; schema class names are format definitions, not evidence of placed objects.',
  defaultBehavior:'Revit walls are room-bounding by default; placed Rooms inherit the view phase automatically. Missing decoded flags do not mean the author needed to configure them manually.',
  references:['https://help.autodesk.com/cloudhelp/2022/ENU/Revit-ArchDesign/files/GUID-241430FC-8084-43A1-AA3A-681B2883B0FC.htm','https://help.autodesk.com/cloudhelp/2022/ENU/Revit-ArchDesign/files/GUID-2D1748B4-D94B-4445-BF90-6C2FDFB4B86E.htm'],
  nextAction:'Run the Revit source inspection/exporter. If native Rooms exist, export their Finish loops and phase-specific door FromRoom/ToRoom. If native Rooms do not exist, wall-derived visitor rooms can remain the primary path; add room-separation lines only where the author verifies an intended partition.'},
 wallInventory:{decodedWalls:walls.length,nativeStraightSolids:walls.filter(e=>e.solid||e.solids?.length).length,nativeArcs:walls.filter(e=>e.arcs?.length).length,nativeFaces:walls.filter(e=>!e.solid&&!e.solids?.length&&!e.arcs?.length&&e.quads?.length).length,boundsOnlyWallCarriers:wallReview.filter(w=>w.reason!=='native-floor-association-unresolved').length,curtainParentsDelegatingGeometry:wallReview.filter(w=>w.reason==='curtain-parent-geometry-delegated').length,decodedCurtainPanels:model.elementBounds.filter(e=>e.categoryName==='Curtain Panels').length,decodedCurtainMullions:model.elementBounds.filter(e=>e.categoryName==='Curtain Wall Mullions').length,unverifiedFootprints:wallReview.filter(w=>w.reason==='native-wall-footprint-unverified').length,missingNativeLevelAssociation:wallReview.filter(w=>w.reason==='native-floor-association-unresolved').length,review:wallReview},
 prioritizedScopes:boundaries.prioritizedScopes.map(scope=>({...scope,nativeFloor:model.levels.find(l=>l.levelId===scope.levelId),nativeWallCarrierReviewIdsOnSharedNativeFloor:wallReview.filter(w=>w.nativeLevelIds.includes(scope.levelId)).map(w=>w.nativeElementId),nextAction:scope.fallback?'Inspect listed fallback rooms and nearby native wall endpoints/columns. Separate millimeter extraction seams from genuinely absent partitions; resolve only with native wall/column support or an author-confirmed separation.':'No unresolved room boundary findings in this scope.'})),
 rooms:fallback.map(r=>({...r,areaKind:records.get(r.roomKey)?.stair?'stair-area':'room',nextAction:records.get(r.roomKey)?.stair?'Inspect native flight/landing coverage, actual openings and anchors. A stair area may intentionally remain open; never fill an opening merely to create a closed room block.':r.nextAction})),
 repairPolicy:'Supported wall-end junction repairs are presentation/preparation evidence, not edits to the source RVT. Preserve original geometry and report native element IDs, repair distance and geometry. Never bridge a modeled doorway, open hallway, atrium, or missing partition solely to make a room look complete.'};
await mkdir(dirname(resolve(out)),{recursive:true});await writeFile(resolve(out),JSON.stringify(report,null,2));console.log(JSON.stringify({fallbackRooms:report.rooms.length,decodedWalls:walls.length,unverifiedWallFootprints:report.wallInventory.unverifiedFootprints,missingWallLevel:report.wallInventory.missingNativeLevelAssociation,topScopes:report.prioritizedScopes.slice(0,5)},null,2));
