/**
 * Regenerate `lib/reviter/revit-2027-class-names.data.ts` from a Revit 2027
 * file's own `Formats/Latest`.
 *
 * The decoders were written against one Revit 2027 project and compare the
 * class index at a partition object's `+16` with that project's numbers. The
 * index is the file's own schema position, and it moves: of the 4,553 classes a
 * 2025 schema shares with the 2027 one, 16 keep their index. The table this
 * writes is the 2027 numbering those constants were read in, kept by name, so
 * `revit-class-tags.ts` can translate any other file's indices into it.
 *
 * Usage:
 *   node --experimental-strip-types scripts/generate-revit-class-tags.ts model-2027.rvt
 */
import { writeFileSync } from "node:fs";

import { openRvt, requireModelPath } from "./lib/rvt-harness.ts";
import { readSchema } from "../lib/reviter/schema-reader.ts";

const OUTPUT = new URL("../lib/reviter/revit-2027-class-names.data.ts", import.meta.url);

const model = openRvt(requireModelPath("generate-revit-class-tags.ts model-2027.rvt"));
model.requireRelease(2027);
const schema = readSchema(model.requireSchema());
if (!schema.ok) throw new Error("Formats/Latest did not read strictly.");
const names = schema.schema.classes.map((entry, position) => {
  if (entry.index !== 12 + position) throw new Error(`Class ${entry.name} is not dense.`);
  return entry.name;
});

writeFileSync(
  OUTPUT,
  `/**
 * The Revit 2027 \`Formats/Latest\` class names in index order, starting at 12.
 *
 * Generated by \`scripts/generate-revit-class-tags.ts\`; do not edit. These are
 * Revit's own schema class names, the numbering every hard-coded class index
 * in the decoders was measured in. See \`revit-class-tags.ts\`.
 */
export const REVIT_2027_FIRST_CLASS_INDEX = 12;

export const REVIT_2027_CLASS_NAMES: readonly string[] = ${JSON.stringify(names)};
`,
);
console.log(`Wrote ${names.length} class names.`);
